### ISSUE TITLE
 Process isAssertion failed in file ../../src/mpid/ch4/shm/posix/eager/include/intel_transport_recv.h at line 1160: cma_read_nbytes == size

### ISSUE THREAD

**Issue by JunxiChhen** [intel/xFasterTransformer#107]
Issue occured:
<img width="1598" alt="image" src="https://github.com/intel/xFasterTransformer/assets/92417411/b3564126-b790-4d18-9808-432a43b3638a">

When running llama2-7b, input4096, output2048, BS16, Beam1, on SPR-HBM flat mode SNC4.
Benchmarking CMD:
<img width="1616" alt="image" src="https://github.com/intel/xFasterTransformer/assets/92417411/cf3fdabc-2237-48dd-aad7-efc32f95eb9e">

**Comment by pujiang2018** [comment]
Looks something wrong with oneCCL. @JunxiChhen Do we still encounter such issue?

**Comment by JunxiChhen** [comment]
> Looks something wrong with oneCCL. @JunxiChhen Do we still encounter such issue?

Yes. But it only occurred on SPR-HBM snc4 flat mode now. I didn't see any issue on SPR Quad mode.

**Comment by pujiang2018** [comment]
@shanzhou2186 Have you ever encountered such issue? for such issue, need an environment to debug.

**Comment by shanzhou2186** [comment]
Have you checked the memory usage on each sub-numa? Is it possible that one of sub numa OOM？

**Comment by shanzhou2186** [comment]
> @shanzhou2186 Have you ever encountered such issue? for such issue, need an environment to debug.

No. I haven't tried such large input/output before.

**Comment by zongy17** [comment]
@JunxiChhen Hi, I also got this error when using  Intel OneAPI (version 2023.2.0). Did you know how to avoid this bug later?
