### ISSUE TITLE
What is the minimum CPU and disk space  configuration?

### ISSUE THREAD

**Issue by baimin1** [intel/xFasterTransformer#114]
THX

**Comment by jackywei** [comment]
For CPU, the bottom line is - the 1st/2nd/3rd gen Xeon Scalable Processor which includes AVX512 (code name=Skylake/CascadeLake/Icelake). The better perf you can get is based on the 4th gen Xeon Scalable Processor with AMX (code name=SapphireRapid: https://www.intel.cn/content/www/cn/zh/products/details/processors/xeon/scalable.html) which includes AMX. Or you can also get the best perf based on Xeon CPU Max which includes both AMX & HBM (https://www.intel.cn/content/www/cn/zh/products/details/processors/xeon/max-series.html).

**Comment by jackywei** [comment]
for the disk, I think it is ok, current mainstream disk has good capacity to hold your LLM models. better to >1TB? it really depends on your LLM models size. you can plan based on that.
