### ISSUE TITLE
Can Windows host be deployed?

### ISSUE THREAD

**Issue by Vincent131499** [intel/xFasterTransformer#117]
As the question, wait patiently for your answer.

**Comment by Duyi-Wang** [comment]
If you want to try xFT on Windows, please ensure your platform supports avx512 instruction at least. If not supports avx512_fp16 & amx, please rebuild package from source following https://github.com/intel/xFasterTransformer/wiki/How-to-build. However, as marvin-Yu said, we do not support Windows natively and Linux is recommended.
