### ISSUE TITLE
Is there any plan to open-source xdnn?

### ISSUE THREAD

**Issue by SpringWave1** [intel/xFasterTransformer#128]
I want to express my appreciation for the incredible work you have done with xft. However, I noticed that the xdnn lib seems not fully open-sourced, is there any plan for this?

**Comment by changqi1** [comment]
oneDNN is an open-sourced repo, and you could reference it.

**Comment by changqi1** [comment]
Welcome to join us with WeChat: https://github.com/intel/xFasterTransformer/wiki

**Comment by SpringWave1** [comment]
> Welcome to join us with WeChat: https://github.com/intel/xFasterTransformer/wiki

Noted, thanks for the explaination.
