### ISSUE TITLE
[bug] library of Intel level-zero not found

### ISSUE THREAD

**Issue by intelyoungway** [intel/xFasterTransformer#134]
### Issue script: 
<xft>/benchmark/run_benchmark.sh
### error message:
```bash
2023:12:15-20:39:37:(61144) |CCL_WARN| could not open the library: libze_loader.so, error: libze_loader.so: cannot open shared object file: No such file or directory
......
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 61144 RUNNING AT worker64
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
```
### CPU
SPR9468
### related version info:
main branch of xFasterTransformer v1.1.0
CentOS8, kernel 5.17.3-1
### other comments:
Such issue is not found in history version;
It took place in both official docker and bare-metal;
**Why do we need Level-Zero in xFasterTransformer?**

**Comment by pujiang2018** [comment]
Level-Zero is imported by oneccl. The warning in most cases does not have issue for distributed inference. it may caused by other issues to crash. What version do you use?
BTW: does the single node without distributed inference work?

**Comment by Duyi-Wang** [comment]
Do you use oneCCL from oneAPI and version is higher than 2024.0? If yes, you can try to downgrade the version to 2023.x and it may works. We find the latest oneCCL in oneAPI may cause problems.

**Comment by Duyi-Wang** [comment]
install `level-zero-devel`
