### ISSUE TITLE
流式输出问题

### ISSUE THREAD

**Issue by Zjq9409** [intel/xFasterTransformer#14]
```
import xfastertransformer
from transformers import AutoTokenizer, TextStreamer
# Assume huggingface model dir is `/data/chatglm-6b-hf` and converted model dir is `/data/chatglm-6b-cpu`.
MODEL_PATH="/data/jane/models/chatglm2-6b-cpu/"
TOKEN_PATH="/data/jane/models/chatglm2-6b"

#INPUT_PROMPT = "Once upon a time, there existed a little girl who liked to have adventures."
INPUT_PROMPT = "问：上海在哪？答: "
tokenizer = AutoTokenizer.from_pretrained(TOKEN_PATH, use_fast=False, padding_side="left", trust_remote_code=True)
streamer = TextStreamer(tokenizer, skip_special_tokens=True, skip_prompt=False)
print(streamer)
input_ids = tokenizer(INPUT_PROMPT, return_tensors="pt", padding=False).input_ids
model = xfastertransformer.AutoModel.from_pretrained(MODEL_PATH, dtype="bf16")
generated_ids = model.generate(input_ids, max_length=200, streamer=streamer)
```

修改了下INPUT_PROMPT 的值，输出不是流式的了，直接一次性输出所有值

**Comment by a3213105** [comment]
我们复现了这个问题，正在处理，稍后给你回复。

**Comment by a3213105** [comment]
应该是streamer的问题，从streamer的源码里可以看出，只有遇到新行或者空格时才会打印，否则就一直cache输出。主要是这个streamer没有专门针对中文的优化。我们也许可以提供一个中文的streamer来解决这个问题。
       
# After the symbol for a new line, we flush the cache.
        if text.endswith("\n"):
            printable_text = text[self.print_len :]
            self.token_cache = []
            self.print_len = 0
# Otherwise, prints until the last space char (simple heuristic to avoid printing incomplete words,
# which may change with the subsequent token -- there are probably smarter ways to do this!)
        else:
            printable_text = text[self.print_len : text.rfind(" ") + 1]
            self.print_len += len(printable_text)

**Comment by a3213105** [comment]
下面的代码是一种work around的方法。你可以试试
model.config(max_length=200)
model.input(input_ids)
while not model.is_done():
    next_tokens = model.forward()
    res = tokenizer.decode(next_tokens[0])
    print(res)
generated_ids = model.finalize()

**Comment by Zjq9409** [comment]
> 下面的代码是一种work around的方法。你可以试试 model.config(max_length=200) model.input(input_ids) while not model.is_done(): next_tokens = model.forward() res = tokenizer.decode(next_tokens[0]) print(res) generated_ids = model.finalize()

这种方式也是一次性输出的。

**Comment by Duyi-Wang** [comment]
升级下transformer，后续版本优化了streamer。pip install transformers==4.33.2。但是不要升级4.34版本，会导致chatGLM的tokenzier不兼容

**Comment by Zjq9409** [comment]
我使用ChatGLM2，在9468上用cache模式，使用12个core性能是 106ms/token，这个性能是正常的么？

**Comment by Zjq9409** [comment]
> 升级下transformer，后续版本优化了streamer。pip install transformers==4.33.2。但是不要升级4.34版本，会导致chatGLM的tokenzier不兼容

使用这个版本可是streamer输出了

**Comment by Zjq9409** [comment]
怎么接收返回的streamer值呢？想用一个参数来接收
