### ISSUE TITLE
[Model] QWen14B-Chat got wrong output when input tokens is too long

### ISSUE THREAD

**Issue by a3213105** [intel/xFasterTransformer#174]
[id.txt](https://github.com/intel/xFasterTransformer/files/13885898/id.txt)
attached is the input tokens 

the output of Torch version is "在正常情况下，框架大车陆侧和海侧的运行速度可以设置为10%、20%、50%和80%，并且可以通过编码器检测的速度控制器进行速度闭环控制。此外，所有的起升机构都有高度参考点，可以根据需要进行速度和位置同步控制。"

and the output of xft is unreadable.

**Comment by changqi1** [comment]
Fixed on https://github.com/intel/xFasterTransformer/pull/179
