### ISSUE TITLE
AMX_int8 not really be used when dtype="int8" 

### ISSUE THREAD

**Issue by yiangyang** [intel/xFasterTransformer#175]
I use 'chatglm-6b.sh' to test the chatglm-6b performance, and I have set the '--dtype int8'. 
But when I use perf to monitor AMX pmu-event, there are no amx int8 event. When dtype is bf16, it work normal:

OS：Ubuntu22.04 kernel 6.5.0
CPU：intel SPR 6430 *2

直接使用chatglm-6b.sh执行benchmark。数据类型bf16可以看到AMX指令正常被调用（perf pmu-event AMX计数器增加），但当数据类型为int8时，没有真正使用AMX指令。
`OMP_NUM_THREADS=32 mpirun -n 1 numactl -N 0 -m 0 sh chatglm-6b.sh : -n 1 numactl -N 1 -m 1 sh chatglm-6b.sh`

如下图：

![image](https://github.com/intel/xFasterTransformer/assets/33369856/5b32d47c-b90b-4eec-9321-db2eafb1b302)
![image](https://github.com/intel/xFasterTransformer/assets/33369856/9ee8355e-bd6f-4d32-9c2c-8a1e24b93758)
![image](https://github.com/intel/xFasterTransformer/assets/33369856/c497024e-cf4c-4986-ab68-ed98b6b78a2c)

**Comment by changqi1** [comment]
@yiangyang  Your observation is right. "-dtype int8" means weight only int8 quantization which use AVX512 to compute MatMul. Your could use "-dtype w8a8" to run AMX-INT8 kernels.

**Comment by yiangyang** [comment]
Got it, thanks！
![image](https://github.com/intel/xFasterTransformer/assets/33369856/f856b5b3-1aba-4f33-9121-868c47d32d03)
