### ISSUE TITLE
Qwen-14B-Chat转换问题

### ISSUE THREAD

**Issue by fengenbao** [intel/xFasterTransformer#185]
```
python /root/xFasterTransformer/tools/qwen_convert.py -i /root/autodl-tmp/Qwen-14B-Chat -o /root/autodl-tmp/Qwen-xft/

=============== Argument ===============
saved_dir: /root/autodl-tmp/Qwen-xft/
in_file: /root/autodl-tmp/Qwen-14B-Chat
processes: 8
weight_data_type: fp16
========================================
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.83it/s]
Fail to save the config in config.ini. 'GenerationConfig' object is not subscriptable
Processing ...
Traceback (most recent call last):
  File "/root/xFasterTransformer/tools/qwen_convert.py", line 262, in <module>
    split_and_convert(args)
  File "/root/xFasterTransformer/tools/qwen_convert.py", line 206, in split_and_convert
    param.detach().cpu().numpy().astype(np_weight_data_type).transpose().tofile(os.path.join(saved_dir, "model.wte.bin"))
TypeError: Got unsupported ScalarType BFloat16
```
请问怎么解决这问题？

**Comment by changqi1** [comment]
@fengenbao  `python ./tools/qwen_convert.py -i /model/qwen-7b-chat-hf/ -o ./qwen-7b-chat-xft -d fp32`

**Comment by Duyi-Wang** [comment]
It's recommended to use this way to convert the model.
```
python -c 'import xfastertransformer as xft; xft.QwenConvert().convert("${HF_DATASET_DIR}","${OUTPUT_DIR}")'
```
And for the fp16 data type, there is a known issue that hasn't been fixed.

**Comment by fengenbao** [comment]
> @fengenbao `python ./tools/qwen_convert.py -i /model/qwen-7b-chat-hf/ -o ./qwen-7b-chat-xft -d fp32` You could use "-d fp32"你可以使用“-d fp32”

![image](https://github.com/intel/xFasterTransformer/assets/57557769/af8775bb-e342-4e55-a1c6-6fbd3840e372)
Still have the same problem

**Comment by fengenbao** [comment]
> @fengenbao `python ./tools/qwen_convert.py -i /model/qwen-7b-chat-hf/ -o ./qwen-7b-chat-xft -d fp32` You could use "-d fp32"你可以使用“-d fp32”
![image](https://github.com/intel/xFasterTransformer/assets/57557769/84840506-6039-4748-b972-31c2cc17f7ca)

Still have the same problem @changqi1

**Comment by fengenbao** [comment]
> It's recommended to use this way to convert the model.建议使用这种方式转换模型。
> 
> ```
> python -c 'import xfastertransformer as xft; xft.QwenConvert().convert("${HF_DATASET_DIR}","${OUTPUT_DIR}")'
> ```
> 
> And for the fp16 data type, there is a known issue that hasn't been fixed.对于fp16数据类型，有一个已知的问题尚未解决。

![image](https://github.com/intel/xFasterTransformer/assets/57557769/5c01196d-9ab8-4f21-9509-d03a6faf6bd1)
I tried,but failed.
@Duyi-Wang 
![image](https://github.com/intel/xFasterTransformer/assets/57557769/f304797d-9986-4cb2-87a1-bff84abfd994)

**Comment by Duyi-Wang** [comment]
I can't reproduce your error, what's your hardware？ Or you can manually set torch device to CPU since it's shouldn't use GPU. We can't verify that because we don't have a GPU....

**Comment by marvin-Yu** [comment]
模型加载的时候会尝试加上flash_attn优化, 导致动态转了数据类型 & 用上了GPU.
https://huggingface.co/Qwen/Qwen-14B-Chat/blob/main/modeling_qwen.py#L941-L988
你可以修改config.json文件中的 `“fp16”: true` + `"use_flash_attn": False`, 先绕过这个问题.
https://huggingface.co/Qwen/Qwen-72B/blob/main/config.json#L12
