### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Storm8878** [intel/xFasterTransformer#186]
After installing version 1.2.0 using pip install xfastrttransformer and converting Qwen-14B Chat, I ran the demo program to obtain the following results. How should I handle this error when it occurs in the `generate` step? 

![image](https://github.com/intel/xFasterTransformer/assets/150501580/9be093d6-be9c-4c84-9ae6-83810465323d)

`lscpu`
![image](https://github.com/intel/xFasterTransformer/assets/150501580/8490652b-2366-4269-b9a6-6c368ff2cbec)

**Comment by Duyi-Wang** [comment]
The default wheel package requires AVX512_fp16 instruction for FP16 and AMX for BF16 and int8. Your CPU is IceLake and doesn't support these instructions. Please use 4th Xeon SapphireRapid for the default configuration. Or you can build xft from source following https://github.com/intel/xFasterTransformer/wiki/How-to-build#build-on-icx--clx to enable xft on ICX platform.

**Comment by Fengenbao123** [comment]
> The default wheel package requires AVX512_fp16 instruction for FP16 and AMX for BF16 and int8. Your CPU is IceLake and doesn't support these instructions. Please use 4th Xeon SapphireRapid for the default configuration. Or you can build xft from source following https://github.com/intel/xFasterTransformer/wiki/How-to-build#build-on-icx--clx to enable xft on ICX platform.

Thanks for your reply.But when I excuted `python3 setup.py bdist_wheel --verbose `, an error occurred.How to solve it?
![image](https://github.com/intel/xFasterTransformer/assets/150501580/90d8f16e-36db-4284-a0e4-c2a7f4ebb3ba)

**Comment by Duyi-Wang** [comment]
There was an error during the compilation of xFT, but the specific error msg is located further up. Please provide the corresponding log. Before running `python3 setup.py bdist_wheel --verbose`, run `python3 setup.py build` once or run a successful build at least once. This is because the packaging program directly records the packaged files at the beginning of execution. If the files generated during compilation do not exist from the start, they will not be included in the wheel package.

**Comment by Storm8878** [comment]
> There was an error during the compilation of xFT, but the specific error msg is located further up. Please provide the corresponding log. Before running `python3 setup.py bdist_wheel --verbose`, run `python3 setup.py build` once or run a successful build at least once. This is because the packaging program directly records the packaged files at the beginning of execution. If the files generated during compilation do not exist from the start, they will not be included in the wheel package.

Thank you for your guidance. I have successfully run it on my IceLake CPU. The instructions I used to test the benchmark are
`numactl -C 0-15 python3 benchmark.py --dtype fp16 --token_in 1024 --token_out 512 --beam_width 1 --batch_size 1 --iteration 1 --warmup 1`
The other parameters have already been set in the source code. I am not sure if I have fully utilized all resources to infer the `Qwen-14B Chat`model, or are there any other techniques or parameters to accelerate inference? Because I saw other people using mpirun or ld_library_path or set OMP_num_threads, but I am not familiar with them.

**Comment by Duyi-Wang** [comment]
> > There was an error during the compilation of xFT, but the specific error msg is located further up. Please provide the corresponding log. Before running `python3 setup.py bdist_wheel --verbose`, run `python3 setup.py build` once or run a successful build at least once. This is because the packaging program directly records the packaged files at the beginning of execution. If the files generated during compilation do not exist from the start, they will not be included in the wheel package.
> 
> Thank you for your guidance. I have successfully run it on my IceLake CPU. The instructions I used to test the benchmark are `numactl -C 0-15 python3 benchmark.py --dtype fp16 --token_in 1024 --token_out 512 --beam_width 1 --batch_size 1 --iteration 1 --warmup 1` The other parameters have already been set in the source code. I am not sure if I have fully utilized all resources to infer the `Qwen-14B Chat`model, or are there any other techniques or parameters to accelerate inference? Because I saw other people using mpirun or ld_library_path or set OMP_num_threads, but I am not familiar with them.

Could you show me your CPU info?

**Comment by Storm8878** [comment]
> > > There was an error during the compilation of xFT, but the specific error msg is located further up. Please provide the corresponding log. Before running `python3 setup.py bdist_wheel --verbose`, run `python3 setup.py build` once or run a successful build at least once. This is because the packaging program directly records the packaged files at the beginning of execution. If the files generated during compilation do not exist from the start, they will not be included in the wheel package.
> > 
> > 
> > Thank you for your guidance. I have successfully run it on my IceLake CPU. The instructions I used to test the benchmark are `numactl -C 0-15 python3 benchmark.py --dtype fp16 --token_in 1024 --token_out 512 --beam_width 1 --batch_size 1 --iteration 1 --warmup 1` The other parameters have already been set in the source code. I am not sure if I have fully utilized all resources to infer the `Qwen-14B Chat`model, or are there any other techniques or parameters to accelerate inference? Because I saw other people using mpirun or ld_library_path or set OMP_num_threads, but I am not familiar with them.
> 
> Could you show me your CPU info?

Because I rented a machine on AutoDL for testing, the results obtained by `lscpu` were not accurate, and the overall situation is as follows

![image](https://github.com/intel/xFasterTransformer/assets/150501580/14c73322-c709-4c94-8227-2a3402a29a4b)

**Comment by Duyi-Wang** [comment]
So, on this machine, can you only use 16 physical cores? These resources may not be sufficient for a smooth LLM experience. Below, I will assume how to fully utilize machine resources when you can use the entire machine.
Firstly, LLM is a computationally intensive task, and hyper-threading doesn't provide much performance improvement. Instead, it can lead to a performance decrease due to scheduling issues. Therefore, when using it, we need to use numactl to avoid using hyper-threading core. Only use `0-31` and `32-63`.
 Secondly, when operating across NUMA nodes to avoid communication between NUMA nodes (which incurs significant latency), we need to deploy in a multi-rank manner using the oneCCL.
```
LD_PRELOAD=libiomp5.so OMP_NUM_THREAD=32 mpirun -n 1 numactl --all -C 0-31 ${CMD} : -n 1 numactl --all -C 32-63 ${CMD}
````
Set OMP_NUM_THREAD to the numbers of your cores. `libiomp5.so` is in the `https://github.com/oneapi-src/oneDNN/releases/download/v0.21/mklml_lnx_2019.0.5.20190502.tgz`

**Comment by Storm8878** [comment]
> So, on this machine, can you only use 16 physical cores? These resources may not be sufficient for a smooth LLM experience. Below, I will assume how to fully utilize machine resources when you can use the entire machine. Firstly, LLM is a computationally intensive task, and hyper-threading doesn't provide much performance improvement. Instead, it can lead to a performance decrease due to scheduling issues. Therefore, when using it, we need to use numactl to avoid using hyper-threading core. Only use `0-31` and `32-63`. Secondly, when operating across NUMA nodes to avoid communication between NUMA nodes (which incurs significant latency), we need to deploy in a multi-rank manner using the oneCCL.
> 
> ```
> LD_PRELOAD=libiomp5.so OMP_NUM_THREAD=32 mpirun -n 1 numactl --all -C 0-31 ${CMD} : -n 1 numactl --all -C 32-63 ${CMD}
> ```
> 
> Set OMP_NUM_THREAD to the numbers of your cores. `libiomp5.so` is in the `https://github.com/oneapi-src/oneDNN/releases/download/v0.21/mklml_lnx_2019.0.5.20190502.tgz`

Thanks for your help.The performance is not good on my third generation processor now. I will try experimenting again when my new fourth generation machine is in place.
