### ISSUE TITLE
4 sockets qwen execute question

### ISSUE THREAD

**Issue by Storm0921** [intel/xFasterTransformer#269]
![image](https://github.com/intel/xFasterTransformer/assets/57557769/a921b411-b742-4a16-9833-088f0e989539)
![image](https://github.com/intel/xFasterTransformer/assets/57557769/9a3b4938-5da5-4b19-8d2e-d2ddf891d342)

Hello, my machine is shown in the above picture, and I want to run the benchmark test of Qwen-14B-Chat with the best performance. What   command should I execute? XFT has been installed in the form of pip.

**Comment by Duyi-Wang** [comment]
Comment code between https://github.com/intel/xFasterTransformer/blob/main/benchmark/run_benchmark.sh#L147 and https://github.com/intel/xFasterTransformer/blob/main/benchmark/run_benchmark.sh#L214, and add following code
```
export OMP_NUM_THREADS=32
run_cmd="mpirun \
    -n 1 bash run.sh 0 0 ${OMP_NUM_THREADS} 0 : \
    -n 1 bash run.sh 1 1 ${OMP_NUM_THREADS} 1 : \
    -n 1 bash run.sh 2 2 ${OMP_NUM_THREADS} 2 : \
    -n 1 bash run.sh 3 3 ${OMP_NUM_THREADS} 3"
```

**Comment by Duyi-Wang** [comment]
The CPU usage should be 50% since it isn't recommended to use hyperthreads. If you can observe that CPU usage is at maximum for CPUs 0-127, then 50% usage is as expected.
You want to run benchmark on 4 numa nodes so 4 instances will be launched by mpirun.

**Comment by Storm0921** [comment]
@Duyi-Wang hello，What should I do if I directly want to mpirun benchmark. py? I'm trying`
OMP_NUM_THREAD=64 mpirun --allow-run-as-root -n 1 numactl -N 0 -C 0-63  python3 benchmark.py: -n 1 numactl -N 1 -C 64-127 python3 benchmark.py`
But it keeps reporting errors
![image](https://github.com/intel/xFasterTransformer/assets/57557769/7cff27e5-c695-4332-b5fd-ddd8e7e6fe37)

![image](https://github.com/intel/xFasterTransformer/assets/57557769/8c58293c-81cc-4907-8270-eaa09b450195)

**Comment by Duyi-Wang** [comment]
use `--all` in numactl.
It's not recommended to run a rank across sockets like `-C 0-63`.
And -N and -C is conflicted. `-N 1` means `-C 32-63,160-191`

**Comment by Storm0921** [comment]
@Duyi-Wang OK，Thanks.When I run OMP_NUM_THREAD=64 mpirun --allow-run-as-root -n 1 numactl --all python3 benchmark.py : -n 1 numactl --all python3 benchmark.py` a new error occurred, what is the reason for it?
![image](https://github.com/intel/xFasterTransformer/assets/57557769/52c4e33c-cb8c-47c5-b547-761fd1a25f01)

**Comment by Duyi-Wang** [comment]
Did you install `mpirun` from `oneCCL`? Please use `oneCCL` and source its environment.
And use `numactl --all -C 0-31` to bind cores.
The value of OMP_NUM_THREADS should be set to 32, ensuring it does not exceed the number of physical cores per node.
You have 4 NUMA nodes, so 4 ranks are required. We introduce multi-rank to avoid running across NUMAs, which can significantly impact performance.

**Comment by Storm0921** [comment]
> You want to run benchmark on 4 numa nodes so 4 instances will be launched by mpirun.

@Duyi-Wang 我很疑惑啊，因为我通过命令运行自然得到的OMP_NUM_THREADS=64，为什么你让我设置32啊？
![image](https://github.com/intel/xFasterTransformer/assets/57557769/a09ca670-3c9b-4c57-9dc6-233245e64388)

**Comment by Duyi-Wang** [comment]
Because the script did not account for the scenario of 4 sockets and 4 NUMA nodes.

**Comment by Storm0921** [comment]
> Because the script did not account for the scenario of 4 sockets and 4 NUMA nodes.

@Duyi-Wang ok,thanks.my command is right to get best performance?
`OMP_NUM_THREAD=32 mpirun -n 1 numactl --all -C 0-31 python3 benchmark.py : -n 1 numactl --all -C 32-63 python3 benchmark.py: -n 1 numactl --all -C 64-95 python3 benchmark.py: -n 1 numactl --all -C 96-127 python3 benchmark.py`
However, executing the above command got stuck.
![image](https://github.com/intel/xFasterTransformer/assets/57557769/b4ddc080-c166-45b9-bcd4-4580bf72c9da)

**Comment by Duyi-Wang** [comment]
Please ensure the path of benchmark.py is `/root/enmotech/xFasterTransformer-main/benchmark/benchmark.py` in your environment.
It's right, and it's recommended to preload libiomp5.so which you can get from https://github.com/oneapi-src/oneDNN/releases/download/v0.21/mklml_lnx_2019.0.5.20190502.tgz

**Comment by Storm0921** [comment]
@Duyi-Wang hello, I have tried in both cases, I believe that the underlying code being executed should be consistent, but why is the difference in results so significant? Buy the way，The parameters are all consistent.
![image](https://github.com/intel/xFasterTransformer/assets/57557769/ef90ea23-1a3e-4c71-a764-2163029cb4ee)

**Comment by Duyi-Wang** [comment]
No idea. Could you show me the modifications you made to the scripts?
