### ISSUE TITLE
[bug] Need to install protobuf library when run benchmark in docker

### ISSUE THREAD

**Issue by xuyizhan** [intel/xFasterTransformer#282]
Hi there,

[Confgiuration]
xFasterTransformer version: 1.4.0
Docker version: Docker version 26.0.0, build 2ae903e
Kernel: 5.15.0

[Steps]
docker pull intel/xfastertransformer:latest
In docker container xfastertransformer run `bash run_benchmark.sh -m llama-2-7b -d bf16 -s 1 -bs 1 -in 1024 -out 128 -i 10`

[Description]
The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. 

`pip install protobuf` will resolve the issue, please help to install necessary library and update the docker image, thanks.

**Comment by marvin-Yu** [comment]
thx~ yizhan, we will fix it at the next release. @Duyi-Wang

**Comment by Duyi-Wang** [comment]
`protobuf` will be added into requirements.txt by this PR #284 and in next docker release.
