### ISSUE TITLE
Build Error: Failure to Download and Configure xdnn_lib

### ISSUE THREAD

**Issue by Damonpkl** [intel/xFasterTransformer#341]
### Description
Encountered an issue where CMake fails to download the MKLML dependency during the build process.

### Steps to Reproduce
1.Pull Docker Image:
docker pull intel/xfastertransformer:latest
2.Test the Qwen2 Conversion:
python -c "import xfastertransformer as xft; xft.Qwen2Convert().convert('/media/model-space/Qwen1___5-14B-Chat', '/media/model-space/Qwen1___5-14B-Chat-xft')"
Note that this command failed.
3.git clone https://github.com/intel/xFasterTransformer.git
4.Configure the project by running cmake .. in the build directory. This step should complete successfully.
![image](https://github.com/intel/xFasterTransformer/assets/87520958/5a970bd5-da20-4df9-b0e0-7cd4afd27016)
5. Run `make j` in the build directory
The build process fails with the following output:
![image](https://github.com/intel/xFasterTransformer/assets/87520958/157cb609-4ff2-4cde-94b8-1df6bebb1f0a)

**Comment by Duyi-Wang** [comment]
This is a network issue.
