### ISSUE TITLE
Memory mapping error on LLaMA 7B w/ 3 ranks

### ISSUE THREAD

**Issue by changqi1** [intel/xFasterTransformer#38]
need to fix the issue on

https://github.com/intel/xFasterTransformer/pull/34/files#diff-a9d9f0516aacc78680023d6fb9b2765388ab390d03239f3b2cc0bdb4f5076f68

and 

MMHelper::packWeight(trans, quantizedGateWeight, gateWeight);

@changqi1

**Comment by heagoo** [comment]
I remember now 3 ranks works.

**Comment by heagoo** [comment]
@changqi1 Do you still see errors? If no, let's close it.
