### ISSUE TITLE
转换模型报错

### ISSUE THREAD

**Issue by zzhint** [intel/xFasterTransformer#4]
你好，我发现在使用xFasterTransformer，转换模型时，出现了以下报错 
python ./tools/llama_convert.py -i /workspace/llama-2-7b-chat-hf/ -o /workspace/llama-2-7b-chat-cpu/

/usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
请问如何解决呢
我怀疑是安装包版本的问题，我看到intel是有docker镜像的，但是我无法pull，请问哪里提供呢

**Comment by Duyi-Wang** [comment]
模型转换时并不涉及xFasterTransformer，使用的是transformer，可以使用docker来看看是否是环境问题。
关于docker镜像，目前dockerhub上拉取还有问题正在解决，可以联系我们获取一个临时的repo地址。
邮件xft.maintainer@intel.com，或者扫描加入微信交流群https://github.com/intel/xFasterTransformer/wiki

**Comment by Duyi-Wang** [comment]
docker image is ready now.
