### ISSUE TITLE
Got a issue "libxfastertransformer_pt.so cannot run in the windows" when start chatglm2

### ISSUE THREAD

**Issue by sxunix** [intel/xFasterTransformer#40]
I made the change on the cli_demo.py according to the guideline. But I got the following issue:

libxfastertransformer_pt.so cannot run in the windows. The error code is 0xc000012f.

would you please help to solve it?

**Comment by sxunix** [comment]
I also attached the error screen here.
![error](https://github.com/intel/xFasterTransformer/assets/5679376/cd962a24-862a-4397-9934-97d41297ffd1)

**Comment by changqi1** [comment]
Currently, we have validated in ubuntu. Do you have a plan to use ubuntu?
