### ISSUE TITLE
gcc8.2 编译报错

### ISSUE THREAD

**Issue by bukejiyu** [intel/xFasterTransformer#419]
![image](https://github.com/intel/xFasterTransformer/assets/52310069/cd1493de-8a6c-4a9f-83a4-c0ca83166f11)

**Comment by pujiang2018** [comment]
To solve this, need to move the kernels into pre-built library. Before that, pls use new GCC.

**Comment by changqi1** [comment]
@bukejiyu Recommend you to use GCC 12.3.0 to build xFT.

**Comment by pujiang2018** [comment]
we now upgraded to PyTorch 2.3, which needs a newer GCC to build cpp_extensions.
