### ISSUE TITLE
[request]qwen1 not supported by vllm-xft

### ISSUE THREAD

**Issue by zhm-algo** [intel/xFasterTransformer#447]
qwen1 not supported by vllm-xft
@pujiang2018

**Comment by heagoo** [comment]
@abenmao Could you please help evaluate the effort?

**Comment by pujiang2018** [comment]
@abenmao Could you please help to evaluate the effort?

**Comment by abenmao** [comment]
> @abenmao Could you please help to evaluate the effort?

I will add this support asap.

**Comment by Duyi-Wang** [comment]
Release v1.7.2 supported.
[#449 ](https://github.com/intel/xFasterTransformer/pull/449)
