### ISSUE TITLE
Update Broken QR Code Link for WeChat on Wiki Page

### ISSUE THREAD

**Issue by w1ida** [intel/xFasterTransformer#472]
Hi team,

I noticed while browsing the wiki page for xFasterTransformer that the QR code intended for WeChat users appears to be either outdated or broken. This can be found at the following location in the repository:
[https://github.com/intel/xFasterTransformer/wiki](https://github.com/intel/xFasterTransformer/wiki)
Upon scanning the QR code, I encountered an error message indicating that the content could not be found. Given that this resource is likely intended to facilitate communication between the project team and Chinese-speaking contributors or users, it's important that this link is functional.

To resolve this issue, I propose updating the QR code image to point to the correct WeChat group or resource. If the intended WeChat group has been disbanded or replaced, please consider linking to an alternative resource or removing the QR code altogether to avoid confusion.

**Comment by Duyi-Wang** [comment]
Updated.
