### ISSUE TITLE
Segmentation fault      (core dumped) FIRST_TOKEN_WEIGHT_LOCATION=$1 NEXT_TOKEN_WEIGHT_LOCATION=$2 OMP_NUM_THREADS=$3 numactl -C $cpu_index -p $2 $BENCHMARK

### ISSUE THREAD

**Issue by LittleNoob2333** [intel/xFasterTransformer#473]
problem:
run command bash run_benchmark.sh -m llama-2-13b -d bf16 -s 2 -bs 1 -in 2048 -out 2  -w 10 -I 1 
meet Segmentation fault      (core dumped) FIRST_TOKEN_WEIGHT_LOCATION=$1 NEXT_TOKEN_WEIGHT_LOCATION=$2 OMP_NUM_THREADS=$3 numactl -C $cpu_index -p $2 $BENCHMARK

env
cpu:8468v
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/4113c852-76c4-4ad6-8bd9-03e37aa9b705">

version:
python=3.10
gcc=9.4.0

compile:
apt-get install libnuma-dev
cd xFasterTransformer
cd 3rdparty
sh prepare_oneccl.sh
cd ..
mkdir build
cd build
cmake -DWITH_TIMELINE=ON ..
make -j
cd ..
python setup.py build
python setup.py install

command:
bash run_benchmark.sh -m llama-2-13b -d bf16 -s 2 -bs 1 -in 2048 -out 2  -w 10 -i 1

**Comment by Moiyu1998** [comment]
I encountered the same issue. How did you resolve it?

**Comment by Duyi-Wang** [comment]
The error occurs because Llama2-13B's maxsupported token length is 2048, and it fails when the sum of the input and output lengths exceeds 2048.
