### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by zwx109473** [intel/xFasterTransformer#475]
Converting the Qwen2 Model Using the python-c'import xfastertransformer as xft;xft.Qwen2Convert().convert("/tmp/models/Qwen2-1.5B-Instruct", "/tmp/xf_models/qweb2_1.5b_xf")' Command

An error is reported during inference execution.
--------------------------
[INFO] SeqLen > FLASH_ATTN_THRESHOLD(8192) will enable FlashAttn.
[INFO] ENABLE_TUNED_COMM is enabled for faster reduceAdd.
[INFO] ENABLE_KV_TRANS is enabled for faster decoding.
[INFO] SINGLE_INSTANCE MODE.
Once upon a time, there existed a little girl who liked to have Illegal instruction (core dumped)
-----------------------------
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      42 bits physical, 48 bits virtual
CPU(s):                             64
On-line CPU(s) list:                0-63
Thread(s) per core:                 2
Core(s) per socket:                 16
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz
Stepping:                           7
CPU MHz:                            3000.000
BogoMIPS:                           6000.00
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          1 MiB
L1i cache:                          1 MiB
L2 cache:                           32 MiB
L3 cache:                           60.5 MiB
NUMA node0 CPU(s):                  0-31
NUMA node1 CPU(s):                  32-63
Vulnerability Gather data sampling: Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:        Processor vulnerable
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology non
                                    stop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowpr
                                    efetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb av
                                    x512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni md_clear flush_l1d arch_capabilities

**Comment by Duyi-Wang** [comment]
"Model name: Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz"
Only support 4th and later Xeon.

**Comment by zwx109473** [comment]
> "Model name: Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz" Only support 4th and later Xeon.
Please provide the supported inter CPU model

**Comment by zwx109473** [comment]
> "Model name: Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz" Only support 4th and later Xeon.

Please provide the supported inter CPU model? @Duyi-Wang

**Comment by Duyi-Wang** [comment]
> > "Model name: Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz" Only support 4th and later Xeon.
> 
> Please provide the supported inter CPU model? @Duyi-Wang
"Model name: Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz" is 2th Xeon(the 2nd number in 6266).
Supported CPU is like X4XX or X5XX.
