### ISSUE TITLE
1st Token Latency Performance Issue for Datatype w8a8

### ISSUE THREAD

**Issue by qiuyuleng1** [intel/xFasterTransformer#477]
I am observing poor 1st token latency for the `w8a8` datatype when using long input lengths, even worse than the `bf16` datatype. This issue is observed across the following models: Llama2 13B, Qwen2 7B, and ChatGLM3-6B. The figure attached below is the result for Llama2 13B.

command:
#socket = 1
#threads = 48
bash run_benchmark.sh -d $data_type -m qwen2-7b -s 1 -bs $batch_size -in $input_lengths -out $output_lengths -i 5 -w 2

![image](https://github.com/user-attachments/assets/c118d528-6deb-4936-994d-632ce638e50f)

**Comment by Duyi-Wang** [comment]
Known issue. Low efficiency of W8A8 and data type conversion for KV cache.

**Comment by Duyi-Wang** [comment]
Default enables flash attention for W8A8 to optimize performance. https://github.com/intel/xFasterTransformer/commit/4f711db9e2818d140577b9eca7b490a3f9a65dc0

**Comment by qiuyuleng1** [comment]
![image](https://github.com/user-attachments/assets/90092723-fd70-4ece-b239-0febcb0ca5a7)
This issue has been resolved. The w8a8 first token latency performance is better than bf16. This issue can now be closed.

**Comment by qiuyuleng1** [comment]
This issue has been resolved. The w8a8 first token latency performance is better than bf16. This issue can now be closed.
