### ISSUE TITLE
libnuma: Warning: node argument 8 is out of range

### ISSUE THREAD

**Issue by marvin-Yu** [intel/xFasterTransformer#57]
In the Docker container, numactl does not recognize the NUMA node for High Bandwidth Memory (HBM). However, using 'numactl -H' reveals the corresponding node. 
will show error:
``` shell
libnuma: Warning: node argument 8 is out of range
```
HW/SW version:
kernel version: 5.15.0-spr.bkc.pc.16.1.23.x86_64
docker version: 24.0.6
host-numactl version: 2.0.16
container-numactl version: 2.0.14-3ubuntu2
docker run option: docker run -e http_proxy -e https_proxy -e no_proxy --privileged  --name wsf-78378ddc4d4ed --rm --detach xftbench-inference-lite:latest

**Comment by pujiang2018** [comment]
I don't think it is the scope of xFT to fix it. (in fact, it cannot be fixed in xFT)
instead, we may need to think about how to launch xFT in case numactl not work.
