### ISSUE TITLE
[numactl] thread binding does not work

### ISSUE THREAD

**Issue by billishyahao** [intel/xFasterTransformer#58]
I observe an issue that when using example binary to run benchmarking, thread binding does not work well. Fix it by taskset.

**Comment by Duyi-Wang** [comment]
Tasket may also fail in certain situations, whether in a host environment or within Docker. If running in a local environment, it is recommended to check the numactl and kernel versions of the operating environment. If running within Docker, you can consider switching to Podman and using containerd to create the environment.

**Comment by Duyi-Wang** [comment]
We found `numactl --all -C` works.
