### ISSUE TITLE
Compile using "python setup install.py" can not find "libxfastertransformer_pt.so"

### ISSUE THREAD

**Issue by JunxiChhen** [intel/xFasterTransformer#66]
When I compiled xFT using "python setup.py install" and run benchmark, an error occurred: 
<img width="755" alt="image" src="https://github.com/intel/xFasterTransformer/assets/92417411/c41e62cc-7d46-4ca2-9077-aab20aa5803a">

When I try to find this by "find / -name libxfastertransformer_pt.so", it shows nothing.

**Comment by Duyi-Wang** [comment]
Please provide the log of `cmake ..`
The compilation of pt.so will be skipped if `torch` is not installed or python is not detected by cmake.

**Comment by Duyi-Wang** [comment]
Please offer the log around warning `PyTorch not found. Skipping torch extension compliling...` if it exists.

**Comment by JunxiChhen** [comment]
I found the .so in 
**/home/workspace/xFasterTransformer/src/xfastertransformer/libxfastertransformer_pt.so**
However, it is not in the pip lib which should be located in:
 **/root/anaconda3/envs/llm/lib/python3.9/site-packages/xfastertransformer-1.0.0-py3.9-linux-x86_64.egg/xfastertransformer/libxfastertransformer_pt.so**
When I copied it manually, it works. But maybe it should be better to be automatically.

**Comment by Duyi-Wang** [comment]
So you compile the so just use `python setup.py install`? 
This a known issue.
run `python setup.py build` first and then `python setup.py install` will be ok as mentioned in the readme.
It records the file which will be packed before the compilation.

**Comment by JunxiChhen** [comment]
It works. Thanks.
