### ISSUE TITLE
Does xFasterTransformer supports Falcon model? 

### ISSUE THREAD

**Issue by amir1m** [intel/xFasterTransformer#74]
Hello,
Planning to run PEFT tuned Falcon model on a CPU (Intel(R) Xeon(R) Platinum 8167M CPU @ 2.00GHz, dockerized Linux). However, the README doesn't mention Falcon, are only listed models supported?

Thanks.

**Comment by pujiang2018** [comment]
Falson was planned, but since we haven't got the strong requirement, thus delayed the support.
And BTW: 8167 is too old, I don't think it will have a good performance without AMX.

**Comment by amir1m** [comment]
> Falson was planned, but since we haven't got the strong requirement, thus delayed the support. And BTW: 8167 is too old, I don't think it will have a good performance without AMX.

Hi @pujiang2018 ,
Which CPU model would you recommend instead?

Thanks.

**Comment by jackywei** [comment]
better to use 94xx/84xx/64xx Xeon Processor:
84xx/64xx(4th Generation Intel® Xeon® Scalable Processors) - https://ark.intel.com/content/www/us/en/ark/products/series/228622/4th-generation-intel-xeon-scalable-processors.html
94xx(Intel® Xeon® CPU Max Series) - https://ark.intel.com/content/www/us/en/ark/products/series/232643/intel-xeon-cpu-max-series.html

**Comment by Duyi-Wang** [comment]
You can join our [WeChat group](https://github.com/intel/xFasterTransformer/wiki) to stay informed about our latest model support initiatives. Your assistance in adjusting the model support arrangements is also greatly welcomed.
