### ISSUE TITLE
cmake file MD5 bug

### ISSUE THREAD

**Issue by waterwoodwind** [intel/xFasterTransformer#97]
-- [download 100% complete]
-- verifying file...
       file='/root/xfastertransformer/build/xdnn_lib-prefix/src/xdnn_v1.1.tar.gz'
-- MD5 hash of
    /root/xfastertransformer/build/xdnn_lib-prefix/src/xdnn_v1.1.tar.gz
  does not match expected value
    expected: 'b55b5d58c92339aa088dcc6e1df6ede2'
      actual: 'b49bf8808d66ea75cfba80a406c9a587'
-- Hash mismatch, removing...
CMake Error at /root/xfastertransformer/build/xdnn_lib-prefix/src/xdnn_lib-stamp/download-xdnn_lib.cmake:170 (message):
  Each download failed!
  
  
  --------
xdnn.cmake
-    URL_HASH          MD5=b55b5d58c92339aa088dcc6e1df6ede2
+   URL_HASH          MD5=b49bf8808d66ea75cfba80a406c9a587
After manual modification, it can be run.

**Comment by marvin-Yu** [comment]
The current version we are using is 1.2.1. The issue is likely caused by our patch 'gitee.diff' not being updated. We will update this patch in the future. In the meantime, you can try manually modifying the dependencies to the latest version. thx~
```shell
$ md5sum *.tar.gz
b49bf8808d66ea75cfba80a406c9a587  xdnn_v1.1.tar.gz
b55b5d58c92339aa088dcc6e1df6ede2  xdnn_v1.2.1.tar.gz
```
