### ISSUE TITLE
Have xFasterTransformer compared with llama.cpp or other inference framwork? which one is faster?

### ISSUE THREAD

**Issue by butterluo** [intel/xFasterTransformer#99]
Have xFasterTransformer compared with llama.cpp or other inference framwork? which one is faster?

**Comment by changqi1** [comment]
Yes, we have compared with llama.cpp. In our test cases, we find xFasterTransformer is better than llama.cpp. But we need to do more test.

**Comment by marvin-Yu** [comment]
XFT (xFasterTransformer) pays more attention to the x86 ecosystem, especially the Xeon series. Feel free to give it a try. Here, we have a step-by-step tutorial based on ali-c8i (Intel-SPR). [Link to tutorial](https://github.com/intel/xFasterTransformer/wiki/Guide-for-User#step-by-step-tutorial)

**Comment by pujiang2018** [comment]
xFasterTransformer is aggressively optimized for Xeon, especially the 4th Xeon (SPR). I believe it has better perf.
If you found some outliers on Xeon, pls tell us.
